### ISSUE TITLE
Change on newest Sponge causing errors

### ISSUE THREAD

**Issue by LucidTheStick** [Arckenver/MightyLoot#1]
MC: 1.10.2
Sponge: spongeforge-1.10.2-2026-5.0.0-BETA-1622.jar
ML: MightyLoot-1.1.jar

Method now takes 2 parameters: BlockType and Cause, rather than just one BlockType.  If this isn't resolved by the time I get home, I can fix it on my dev machine and PR it.

Files:
https://github.com/Arckenver/MightyLoot/blob/722c6b498d2bb16244aa4af528385a938f8b6a75/src/main/java/com/arckenver/mightyloot/DataHandler.java
https://github.com/Arckenver/MightyLoot/blob/722c6b498d2bb16244aa4af528385a938f8b6a75/src/main/java/com/arckenver/mightyloot/task/SpawnLootRunnable.java

Error:

```
[14:46:34] [Server thread/ERROR] [Sponge/]: The Scheduler tried to run the task MightyLoot - SpawnLoot Task - world owned by org.spongepowered.mod.plugin.SpongeModPluginContainer@4c1b3e5d, but an error occured.
java.lang.NoSuchMethodError: org.spongepowered.api.world.Location.setBlockType(Lorg/spongepowered/api/block/BlockType;)V
    at com.arckenver.mightyloot.task.SpawnLootRunnable.run(SpawnLootRunnable.java:83) ~[SpawnLootRunnable.class:1.1]
    at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2026-5.0.0-BETA-1622]
    at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2026-5.0.0-BETA-1622]
    at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.10.2-2026-5.0.0-BETA-1622]
    at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.10.2-2026-5.0.0-BETA-1622]
    at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.10.2-2026-5.0.0-BETA-1622]
    at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_91]
    at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.10.2-2026-5.0.0-BETA-1622]
    at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.10.2-2026-5.0.0-BETA-1622]
    at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2026-5.0.0-BETA-1622]
    at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:242) [SpongeMod.class:1.10.2-2026-5.0.0-BETA-1622]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:129) [EventBus.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:98) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by Arckenver** [comment]
Indeed. Version 1.1 of MightyLoot targets SpongeAPI v4.x.x

I'm creating a new branch for v2.0 that will target v5.x.x of the API. Feel free to PR it to solve this, your contribution would be highly appreciated !
