### ISSUE TITLE
Console stacktrace - Scheduler?

### ISSUE THREAD

**Issue by ProsperCraft** [Arckenver/MightyLoot#14]
https://gist.github.com/ProsperCraft/d299e52ba3b0ea0d370f4751bc93e153

```
[23:46:23] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task MightyLoot - SpawnLoot Task - world-infinitylite owned by Plugin{id=mightyloot, name=MightyLoot, version=2.1, description=A treasurehunt-like sponge plugin., url=https://github.com/Arckenver/MightyLoot, authors=[Arckenver], source=/opt/infinitylite/./plugins/MightyLoot-2.1.jar}, but an error occured.
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_111]
        at com.arckenver.mightyloot.DataHandler.removeLoot(DataHandler.java:33) ~[DataHandler.class:2.1]
        at com.arckenver.mightyloot.task.SpawnLootRunnable.run(SpawnLootRunnable.java:48) ~[SpawnLootRunnable.class:2.1]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2107-6.0.0-BETA-1873]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2107-6.0.0-BETA-1873]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.10.2-2107-6.0.0-BETA-1873]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.10.2-2107-6.0.0-BETA-1873]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.10.2-2107-6.0.0-BETA-1873]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_111]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.10.2-2107-6.0.0-BETA-1873]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.10.2-2107-6.0.0-BETA-1873]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2107-6.0.0-BETA-1873]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:258) [SpongeMod.class:1.10.2-2107-6.0.0-BETA-1873]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:125) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Arckenver** [comment]
This will be fixed in the next version of MightyLoot.

Thanks for reporting.
